# Generated by Django 2.1.1 on 2018-10-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='batch',
            field=models.CharField(default=None, max_length=256, unique=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='division',
            field=models.CharField(default=None, max_length=256, unique=True),
        ),
    ]
