# Generated by Django 2.1.1 on 2018-10-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20181008_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='lecture',
            field=models.CharField(default=None, max_length=256, unique=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='lecturer',
            field=models.CharField(default=None, max_length=256, unique=True),
        ),
    ]
