# Generated by Django 2.1.1 on 2018-10-12 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_loggeduser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loggeduser',
            old_name='username',
            new_name='name',
        ),
    ]
