# Generated by Django 2.1.1 on 2018-10-12 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20181012_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loggeduser',
            old_name='name',
            new_name='username',
        ),
    ]
