# Generated by Django 2.1.1 on 2018-10-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20181012_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loggeduser',
            old_name='username',
            new_name='name',
        ),
        migrations.AddField(
            model_name='loggeduser',
            name='present_students',
            field=models.CharField(default='Absent', max_length=10),
        ),
    ]
