# Generated by Django 2.1.1 on 2018-10-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20181012_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='rollnumber',
            field=models.IntegerField(default='0'),
        ),
    ]
