# Generated by Django 2.1.1 on 2018-10-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_userprofileinfo_rollnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggeduser',
            name='attendence',
            field=models.CharField(default='Absent', max_length=30),
        ),
    ]
