# Generated by Django 2.1.1 on 2018-10-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_loggeduser_attendence'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggeduser',
            name='rollnumber',
            field=models.IntegerField(default='0'),
        ),
    ]
