# Generated by Django 2.1.1 on 2018-10-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_loggeduser_rollnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggeduser',
            name='rollnumber',
            field=models.CharField(default='0', max_length=7),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='rollnumber',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
