# Generated by Django 2.1.1 on 2018-10-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_auto_20181012_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggeduser',
            name='enteredkey',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
