# Generated by Django 2.1.1 on 2018-10-23 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_adminregistration_adminregistrationmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminregistration',
            old_name='profile_pic1',
            new_name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='adminregistration',
            name='lecture',
        ),
        migrations.RemoveField(
            model_name='adminregistration',
            name='lecturer',
        ),
    ]
