# Generated by Django 2.1.1 on 2018-10-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_auto_20181023_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminregistration',
            name='user',
        ),
        migrations.AddField(
            model_name='adminregistrationmodel',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='login/media/admin'),
        ),
        migrations.DeleteModel(
            name='AdminRegistration',
        ),
    ]
